### ISSUE TITLE
Question about the Mars Rovers API

### ISSUE THREAD

**Issue by Orbyt** [nasa/NASA-APIs#10]
I noticed that for the past couple of days there hasnt been any new images released in the [Mars Rover Photos API](https://api.nasa.gov/api.html#MarsPhotos), for example: https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/photos?earth_date=2015-12-3&api_key=DEMO_KEY

Dec 3, Dec 2, and Dec 1 are all empty. I was wondering if there was simply no images taken on those days, or is the data congregated for a bit and then released all at once at a later time? 

Eg. how long does it take to get the images accessible from the API?

**Comment by phillc73** [comment]
I guess this must have been a temporary glitch. There are images now at the URL you've provided. I've also tried with yesterday's date (2016-02-18), and also had images returned.

**Comment by brianthomas** [comment]
Can we resolve and close then?

**Comment by Orbyt** [comment]
This issue is fairly old. I ended up getting in touch with the maintainer of the API and the update time was improved a bit. Closed
