### ISSUE TITLE
Curiosity Json data feed broken for historic data

### ISSUE THREAD

**Issue by open768** [nasa/NASA-APIs#11]
HI Jason, 

I noticed that the JPL Json feed for curiosity when accessing **historic data** is returning  an access denied message.

**an example of a url that returns the error is**
http://mars.jpl.nasa.gov/msl-raw-images/image/images_sol10.json

which is obtained from the manifest at 
http://mars.jpl.nasa.gov/msl-raw-images/image/image_manifest.json

**the error is**
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>AEE0FE243C3E16BF</RequestId>
<HostId>
ghiiRdKjHIVMd4CARBGmDpnvKXlpNbMdUDl1pLbYf/ryGIdkQh8reg/bJC5S9hdkJp881Di3kqk=
</HostId>
</Error>

**an example of a url that provides a valid response is**

http://mars.jpl.nasa.gov/msl-raw-images/image/images_sol1201.json

**Comment by phillc73** [comment]
I guess this must have been a temporary glitch. I'm seeing data returned at the error example URL you've provided. Maybe the servers took a couple of days off for Christmas!

**Comment by JustinGOSSES** [comment]
Issue has been fixed so will be closing.
