### ISSUE TITLE
Query string not working for Sounds API

### ISSUE THREAD

**Issue by phillc73** [nasa/NASA-APIs#12]
The query string parameter for the Sounds API doesn't seem to make any difference to the results returned.

e.g.
https://api.nasa.gov/planetary/sounds?q=kepler&limit=100&api_key=DEMO_KEY
https://api.nasa.gov/planetary/sounds?q=apollo&limit=100&api_key=DEMO_KEY

Both queries return exactly the same results.

I've also used my own API Key with the same outcome.

**Comment by phillc73** [comment]
I've managed to find a workaround for this. 

If the queries are altered to use "query" rather than "q", different and relevant results are returned.

https://api.nasa.gov/planetary/sounds?query=kepler&limit=100&api_key=DEMO_KEY
https://api.nasa.gov/planetary/sounds?query=apollo&limit=100&api_key=DEMO_KEY

Looks like the documentation just needs updating at: https://api.nasa.gov/api.html#sounds

**Comment by JustinGOSSES** [comment]
Thank you for the comment. Sounds API is now defunct, so I will be closing this issue. 

Similar content can be found on:
https://soundcloud.com/nasa
&
https://soundcloud.com/nasa
