### ISSUE TITLE
APOD - api not sending new photo

### ISSUE THREAD

**Issue by Cyclokitty** [nasa/NASA-APIs#17]
Using the https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY address, I'm getting back a Heroku page that says there is an Application Error. 

My github page uses Axios and React to retrieve the APOD and I'm getting back a 503 (service unavailable) message in the console.

**Comment by jnbetancourt** [comment]
We've recently redeployed the APOD API, which should fix the issue.
