### ISSUE TITLE
https://open.nasa.gov/developer/ Site is down

### ISSUE THREAD

**Issue by joelibaceta** [nasa/NASA-APIs#22]
<img width="733" alt="captura de pantalla 2018-11-26 a la s 22 17 31" src="https://user-images.githubusercontent.com/864790/49052058-13572980-f1c9-11e8-9498-f58b7a596d7d.png">

**Comment by JustinGOSSES** [comment]
Didn't find that link when I ran a scan for dead links in early January. Can you please supply the page where that URL is linked from?

**Comment by JustinGOSSES** [comment]
closing as I can't find where that link is in the page and that page shouldn't exist.
