### ISSUE TITLE
equivalent feed for other rovers to http://mars.jpl.nasa.gov/msl-raw-images/image/image_manifest.json

### ISSUE THREAD

**Issue by open768** [nasa/NASA-APIs#5]
I'm using the json feed published by JPL (http://mars.jpl.nasa.gov/msl-raw-images/image/image_manifest.json) to write a social browser for MSL data at http://www.mars-tourist-guide.co.uk/curiosity/.

is there an equivalent API for spirit and opportunity that can be used?

NB the MSL api doesnt appear to be listed on open.nasa.

**Comment by open768** [comment]
dang the undocumented JPL feed is broken :-(

eg 
http://mars.jpl.nasa.gov/msl-raw-images/image/images_sol1000.json

gives 

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>149E9EA72827E80F</RequestId>
<HostId>
Pb7ksdY+zAokVJThEkSHxhKMVkH5XN/fkIr7OtORv2+HJ0/Ydi4YNmI9ew3X4Wo7KiJ+PBwI/ng=
</HostId>
</Error>

**Comment by JustinGOSSES** [comment]
This problem appears to no longer apply to the current API for this class of data, so I'm closing.
