### ISSUE TITLE
Best API

### ISSUE THREAD

**Issue by migmacdev** [nasa/NASA-APIs#7]
Hi my question is about wich API to use, basically what I need is to know the position of the planets at a given date, from thousand years B.C and A.D.

For example if a user want to know where was mars in the 1st day of july of year 200 B.C.

Thanks.

**Comment by MichalPaszkiewicz** [comment]
I am looking for something similar and as far as I can tell, this is the best API: http://www.astro-phys.com/api

Although it gives the planet's position as x, y, z coordinates.

**Comment by JustinGOSSES** [comment]
This is old and not really an issue exactly, more of a question that seems answered, so I'm going to close it.
