### ISSUE TITLE
get_tag_datasets not working

### ISSUE THREAD

**Issue by jbrave** [nasa/NASA-APIs#8]
It appears that none of the APIs on this page are working. 
http://data.nasa.gov/api-info/#get_tag_datasets

{

```
"status": "error",
"error": "Uknown method 'get_dataset'."
```

}

get_recent_datasets
get_dataset
get_date_datasets
get_category_datasets
get_tag_datasets
get_search_results
get_date_index
get_category_index
get_tag_index - See more at: http://data.nasa.gov/api-info/#get_tag_datasets

**Comment by qanx** [comment]
I am so glad that I'm not the only one experiencing this issue - I have been pounding my head against this trying to figure out what was wrong. Unfortunately that means this still isn't resolved 1+ month later.

**Comment by Nomad-Mystic** [comment]
I feel the same way been trying to make this work for a few hours today. The site clearly outlines the methods of the API but none of them seem to be working....

**Comment by qanx** [comment]
I tried reaching out to them directly via email but that failed as well. I really wish I knew what was going on with this.

**Comment by open768** [comment]
http://data.nasa.gov/api/get_category_index works fine

**Comment by qanx** [comment]
Yes, and that is the only one. If you try any of the others, even the examples, they do not work. For example:

http://data.nasa.gov/api/get_recent_datasets/

If you work through the API commands, almost all of them are not working :(

**Comment by open768** [comment]
guess you've tried opengov@nasa.gov. or you can try jason duley who wrote the api.

**Comment by qanx** [comment]
When I did I just received a delivery failed/email does not exist error. What is the best way to reach Jason Duley?

**Comment by jbrave** [comment]
I got in contact with @bethbeck who appears to be the party responsible for the API team & she said they are working on it(sorta):
https://twitter.com/bethbeck/status/567408663103803393

**Comment by qanx** [comment]
Thank you! :D

**Comment by qanx** [comment]
No one else commented here so I figured I'd mention that it looks like the NASA team updated and that the old API is now defunct. More info:

https://data.nasa.gov/about

**Comment by JustinGOSSES** [comment]
this problem is no longer a problem as that API is now defunt, so closing.
